---
- name: provision new azure host
  hosts: localhost
  connection: local
  vars_files:
      - vars.yml

  tasks:
  - name: create Azure resource group
    azure_rm_resourcegroup:
      name: '{{azure_resource_group}}'
      location: australiaeast
      state: present

  - name: create Azure virtual network in resource group
    azure_rm_virtualnetwork:
      name: '{{azure_virtual_network}}'
      resource_group: '{{azure_resource_group}}'
      address_prefixes_cidr:
      - 10.1.0.0/16
      state: present
  
  - name: create Azure subnet in virtualnetwork
    azure_rm_subnet:
      name: '{{azure_subnet}}'
      state: present
      virtual_network_name: '{{azure_virtual_network}}'
      resource_group: '{{azure_resource_group}}'
      address_prefix_cidr: 10.1.0.0/24

  - name: create Azure storage account
    azure_rm_storageaccount:
      name: '{{azure_storage_account}}'
      resource_group: '{{azure_resource_group}}'
      account_type: Standard_LRS

  - name: provision new Azure virtual host
    azure_rm_virtualmachine:
      admin_username: '{{azure_vm_username}}'
      admin_password: '{{azure_vm_password}}'
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
      name: '{{azure_virtual_machine}}'
      resource_group: '{{azure_resource_group}}'
      state: present
      vm_size: Standard_DS1_v2
      storage_account_name: '{{azure_storage_account}}'
      virtual_network_name: '{{azure_virtual_network}}'
      subnet_name: '{{azure_subnet}}'

  - name: create Azure vm extension to enable HTTPS WinRM listener
    azure_rm_virtualmachine_extension:
      name: winrm-extension
      resource_group: '{{azure_resource_group}}'
      virtual_machine_name: '{{azure_virtual_machine}}'
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: 1.9
      settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
      auto_upgrade_minor_version: true

